-- insert into projects(name, event_type, brides_name, grooms_name, notes, budget, business_id, modified_date, created_date) values('Shiva weds pooja project', 'WEDDING', 'Pooja Vadaa', 'Shiva Komatreddy', 'hello world', 10000.00, 1, 20200527, 20200527);
-- select * from projects as p
-- left join tasks  on tasks.projectId = p.id
-- where p.id = 1;